#!/usr/bin/env node
/**
 * Bộ hiệu chuẩn gu hình (CHARTER 6.8b, mặc định M2).
 *
 * Ba lệnh:
 *   --pair <file>                       in thân issue so sánh cặp
 *   --record --pair <id> --choice A|B|= ghi một lựa chọn vào log
 *   --tally                             tính độ nhất quán theo trục
 *
 * Quy trình đầy đủ ở `docs/visual/calibration.md`.
 *
 * Vì sao script này tồn tại thay vì làm tay: lựa chọn của chủ dự án là
 * nguồn DUY NHẤT của gu hình kênh này, nên nó phải được ghi ở dạng máy đọc
 * được ngay từ lúc thu, không phải được tóm tắt lại sau.
 */

import { readFileSync, readdirSync, existsSync, appendFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';

const root = process.cwd();
const pairsDir = join(root, 'docs', 'visual', 'pairs');
const logPath = join(root, 'docs', 'visual', 'calibration-log.jsonl');

export interface Pair {
  id: string;
  axis: string;
  question: string;
  variantA: { label: string; params: Record<string, number> };
  variantB: { label: string; params: Record<string, number> };
  renderRef: { a: string; b: string } | null;
  note: string;
}

export type Choice = 'A' | 'B' | '=';

export interface LogLine {
  at: string;
  pairId: string;
  axis: string;
  choice: Choice;
  issue?: number;
  /** Lựa chọn của bộ chấm tự động, nếu đã có (mục V-005). */
  auto?: Choice;
  /** Dòng đính chính cho một lựa chọn trước đó. Log là append-only. */
  supersedes?: string;
}

export function loadPair(path: string): Pair {
  return JSON.parse(readFileSync(path, 'utf8')) as Pair;
}

export function loadAllPairs(): Pair[] {
  if (!existsSync(pairsDir)) return [];
  return readdirSync(pairsDir)
    .filter((f) => f.endsWith('.json'))
    .map((f) => loadPair(join(pairsDir, f)))
    .sort((a, b) => (a.id < b.id ? -1 : 1));
}

function paramLine(params: Record<string, number>): string {
  return Object.entries(params)
    .map(([k, v]) => `\`${k} = ${v}\``)
    .join(', ');
}

/**
 * Thân issue. Phải đọc và trả lời được trong khoảng 60 giây trên màn hình
 * điện thoại (rủi ro B11), nên nó ngắn và không có thuật ngữ chưa giải thích.
 */
export function issueBody(pair: Pair): string {
  const images = pair.renderRef
    ? [`| ![A](${pair.renderRef.a}) | ![B](${pair.renderRef.b}) |`, '|---|---|', '| **A** | **B** |', '']
    : [
        '> Chưa có ảnh: phòng thí nghiệm layout (mục `V-003`) chưa xong.',
        '> Trả lời theo mô tả cũng được — lựa chọn vẫn dùng được, chỉ kém chắc chắn hơn.',
        '',
      ];

  return [
    `🤖 **${pair.question}**`,
    '',
    ...images,
    `**A** — ${pair.variantA.label}`,
    `**B** — ${pair.variantB.label}`,
    '',
    `Điều duy nhất khác nhau: ${pair.note}`,
    '',
    '---',
    '',
    '**Trả lời:** comment một chữ `A`, `B`, hoặc `=` nếu anh không thấy khác biệt đáng kể.',
    '',
    '`=` là một câu trả lời có ích, không phải né tránh: nó nói rằng trục này không đáng làm cổng, và tiết kiệm cho anh hai mươi cặp nữa.',
    '',
    '<details><summary>Chi tiết kỹ thuật</summary>',
    '',
    `- Trục: \`${pair.axis}\` · Cặp: \`${pair.id}\``,
    `- A: ${paramLine(pair.variantA.params)}`,
    `- B: ${paramLine(pair.variantB.params)}`,
    `- Đủ ≥20 cặp trên trục này thì kết quả thành ngưỡng trong \`packs/genres/<genre>/format-spec.json\`, qua một PR riêng.`,
    '',
    '</details>',
    '',
    '---',
    '_Generated by [Claude Code](https://claude.ai/code)_',
  ].join('\n');
}

export function issueTitle(pair: Pair): string {
  return `🤖 [Gu hình] ${pair.axis} · cặp ${pair.id}`;
}

export function readLog(text: string): LogLine[] {
  return text
    .split('\n')
    .filter((line) => line.trim() !== '')
    .map((line) => JSON.parse(line) as LogLine);
}

export interface AxisTally {
  axis: string;
  answered: number;
  ties: number;
  /**
   * Độ nhất quán: tỷ lệ lựa chọn nghiêng về phía đông hơn của trục.
   * Gần 1.0 là gu rõ. Gần 0.5 nghĩa là trục này không đáng làm cổng —
   * đó là một kết quả, không phải một thất bại.
   */
  consistency: number;
  /** Tỷ lệ bộ chấm tự động chọn giống chủ dự án. Cổng theo CHARTER 6.8c. */
  autoAgreement: number | null;
  autoScored: number;
  gateReady: boolean;
}

export const GATE_MIN_PAIRS = 20;
export const GATE_MIN_AGREEMENT = 0.9;

/** Dòng đính chính thay thế dòng cũ; log vẫn append-only. */
export function effectiveLines(lines: readonly LogLine[]): LogLine[] {
  const superseded = new Set(lines.map((l) => l.supersedes).filter((v): v is string => !!v));
  const byPair = new Map<string, LogLine>();
  for (const line of lines) {
    if (superseded.has(line.pairId) && !line.supersedes) continue;
    byPair.set(line.pairId, line);
  }
  return [...byPair.values()];
}

export function tally(lines: readonly LogLine[]): AxisTally[] {
  const axes = new Map<string, LogLine[]>();
  for (const line of effectiveLines(lines)) {
    const bucket = axes.get(line.axis) ?? [];
    bucket.push(line);
    axes.set(line.axis, bucket);
  }

  return [...axes.entries()]
    .map(([axis, entries]) => {
      const decided = entries.filter((e) => e.choice !== '=');
      const ties = entries.length - decided.length;
      const a = decided.filter((e) => e.choice === 'A').length;
      const consistency =
        decided.length === 0 ? 0 : Math.max(a, decided.length - a) / decided.length;

      const autoScored = entries.filter((e) => e.auto !== undefined).length;
      const agreed = entries.filter((e) => e.auto !== undefined && e.auto === e.choice).length;
      const autoAgreement = autoScored === 0 ? null : agreed / autoScored;

      return {
        axis,
        answered: entries.length,
        ties,
        consistency: Number(consistency.toFixed(4)),
        autoAgreement: autoAgreement === null ? null : Number(autoAgreement.toFixed(4)),
        autoScored,
        gateReady:
          autoScored >= GATE_MIN_PAIRS &&
          autoAgreement !== null &&
          autoAgreement >= GATE_MIN_AGREEMENT,
      };
    })
    .sort((x, y) => (x.axis < y.axis ? -1 : 1));
}

// ── CLI ──────────────────────────────────────────────────────────────────

function arg(name: string): string | undefined {
  const i = process.argv.indexOf(`--${name}`);
  return i === -1 ? undefined : process.argv[i + 1];
}

const isMain = process.argv[1]?.endsWith('calibration.ts') === true;

if (isMain) {
  if (process.argv.includes('--record')) {
    const id = arg('pair');
    const choice = arg('choice') as Choice | undefined;
    if (!id || !choice || !['A', 'B', '='].includes(choice)) {
      process.stderr.write('Cần --pair <id> và --choice A|B|=\n');
      process.exit(2);
    }
    const path = join(pairsDir, `${id}.json`);
    if (!existsSync(path)) {
      process.stderr.write(`Không có cặp "${id}" trong docs/visual/pairs/.\n`);
      process.exit(2);
    }
    const pair = loadPair(path);
    const issue = arg('issue');
    const line: LogLine = {
      at: new Date().toISOString(),
      pairId: pair.id,
      axis: pair.axis,
      choice,
      ...(issue ? { issue: Number(issue) } : {}),
      ...(arg('supersedes') ? { supersedes: arg('supersedes')! } : {}),
    };
    mkdirSync(dirname(logPath), { recursive: true });
    appendFileSync(logPath, `${JSON.stringify(line)}\n`, 'utf8');
    process.stdout.write(`Đã ghi: ${pair.id} → ${choice}\n`);
  } else if (process.argv.includes('--tally')) {
    const lines = existsSync(logPath) ? readLog(readFileSync(logPath, 'utf8')) : [];
    const rows = tally(lines);
    if (rows.length === 0) {
      process.stdout.write(
        'Chưa có lựa chọn nào trong docs/visual/calibration-log.jsonl.\n' +
          `Có ${loadAllPairs().length} cặp đã soạn sẵn. Mục V-004 trong backlog làn visual là mục chạy vòng lặp này.\n`,
      );
    } else {
      process.stdout.write('trục            đã chọn  hoà  nhất quán  trùng bộ chấm  cổng\n');
      for (const r of rows) {
        process.stdout.write(
          `${r.axis.padEnd(15)} ${String(r.answered).padStart(7)}  ${String(r.ties).padStart(3)}  ` +
            `${r.consistency.toFixed(2).padStart(9)}  ` +
            `${(r.autoAgreement === null ? '—' : r.autoAgreement.toFixed(2)).padStart(13)}  ` +
            `${r.gateReady ? 'sẵn sàng' : 'chưa'}\n`,
        );
      }
      process.stdout.write(
        `\nCổng bộ chấm tự động (CHARTER 6.8c): ≥${GATE_MIN_AGREEMENT * 100}% trên ≥${GATE_MIN_PAIRS} cặp.\n` +
          'Chưa đạt thì bộ chấm chỉ cảnh báo, không chặn.\n',
      );
    }
  } else {
    const path = arg('pair');
    if (!path) {
      process.stderr.write(
        'Dùng: --pair <file.json> | --record --pair <id> --choice A|B|= | --tally\n',
      );
      process.exit(2);
    }
    const pair = loadPair(path.endsWith('.json') ? path : join(pairsDir, `${path}.json`));
    process.stdout.write(`${issueTitle(pair)}\n\n${issueBody(pair)}\n`);
  }
}
